package com.easyfield.attendance.response.attendancedetail

data class Activity(
    val amount: String,
    val amount_details: String,
    val amount_type: String,
    val approved_amount: Int,
    val category_id: Int,
    val category_name: String,
    val city_id: Int,
    val city_name: String,
    val collection_of: String,
    val created_at: String,
    val discussion_point: String,
    val duration: String,
    val expense_details: String,
    val expense_photo: String,
    val extra: String,
    val id: Int,
    val is_first: Boolean,
    val latitude: Double,
    val longitude: Double,
    val party_id: Int,
    val party_name: String,
    val payments_details: String,
    val payments_photo: String,
    val place: String,
    val remarks: String,
    val requested_amount: Int,
    val status_id: Int,
    val status_name: String,
    val time: String,
    val type: String
)